Repository 1024pix/pix-site, pull requests merged in 2020-10, with the labels that each got.

#178 [FEATURE] Intégrer la sous-navigation de pix-pro (PIX-1265)
  components/BurgerMenuNav.vue
  components/NavigationSliceZone.vue
  components/OrganizationNav.vue
  components/PixProSubNav.vue
  components/slices/LogosZone.vue
  nuxt.config.js
  static/images/logo-pix_pro_279x114.png
  store/index.js
Labels: Tech Review OK, cross-team, team-evaluation, team-prescription

#180 [TECH] Amélioration du temps de chargement des pages.
  nuxt.config.js
  pages/pix-site/index.vue
  static/images/background-hero-index.jpg
  static/images/background-hero-mobile-index.jpg
Labels: cross-team

#181 [FEATURE] Modification du titre du bloc pour structure de page et a11y (PIX-1309)
  components/slices/Features.vue
Labels: Func Review OK, Tech Review OK, team-evaluation

#179 [FEATURE] Création du bloc process (PIX-1198).
  components/SliceZone.vue
  components/slices/Process.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#185 [FEATURE] Ajouter la possibilité de mettre une vidéo sur Article (PIX-1310).
  components/slices/Article.vue
Labels: :rocket: Ready To Merge, team-evaluation

#183 [TECH] Ajouter des tests pour LogosZone.
  tests/components/slices/LogosZone.test.js
Labels: :rocket: Ready To Merge, team-evaluation

#187 [BUGFIX] Pouvoir cliquer sur l'icon du bouton dropdown de la navigation
  components/slices/NavigationZone.vue
Labels: Func Review Needed, Tech Review Needed, hacktoberfest-accepted, team-evaluation

#192 [CLEANUP] Retirer la balise H1 déjà prise en compte par prismic-rich-text.
  components/SimplePage.vue
Labels: Tech Review Needed, cross-team, hacktoberfest-accepted, team-evaluation

#194 [BUGFIX] Gestion des liens sur Pix-pro.
  components/PixLink.vue
  components/slices/PageSection.vue
Labels: Tech Review Needed, hacktoberfest-accepted, team-evaluation

#195 [BUGFIX] Fix appel à /undefined (PIX-1402).
  components/slices/Article.vue
Labels: Tech Review Needed, team-evaluation

#196 [BUGFIX] Empêcher les getSingle of undefined sur Pix.org (PIX-1404).
  plugins/i18n.js
  store/index.js
Labels: Tech Review Needed, hacktoberfest-accepted, team-evaluation

#189 [TECH Ajout de commentaires de PR automatique contenant les urls des review apps.
  .github/pull_request_template.md
  .nvmrc
  package.json
  scripts/signal_deploy_to_pr.sh
Labels: Func Review OK, Tech Review OK, cross-team

#191 [CLEANUP] Pouvoir utiliser les slices pages coté pix-pro.
  pages/pix-pro/_custom-page.vue
  pages/pix-pro/_simple-page.vue
Labels: Tech Review Needed, cross-team, hacktoberfest-accepted, team-evaluation, team-prescription

#197 Mise en place du nouveau Matomo
  nuxt.config.js
Labels: Tech Review Needed

#190 [FEATURE] Avoir une navigation principale pour Pix Pro (PIX-1368).
  components/BurgerMenuNav.vue
  components/NavigationSliceZone.vue
  package-lock.json
  package.json
  plugins/i18n.js
  services/document-fetcher.js
  store/index.js
  tests/components/slices/NavigationSliceZone.test.js
  tests/services/document-fetcher.test.js
Labels: Func Review Needed, Tech Review Needed, hacktoberfest-accepted, team-evaluation, team-prescription

#200 [TECH] Aligner les couleurs de pix-site
  assets/scss/components/_main-nav.scss
  assets/scss/globals/_colors.scss
  assets/scss/shared/_buttons.scss
  assets/scss/shared/_normalize.scss
  assets/scss/shared/_pages.scss
  assets/scss/shared/_text.scss
  assets/scss/shared/_titles.scss
  components/AppFooter.vue
  components/BurgerMenuNav.vue
  components/CtaButton.vue
  components/FormablePage.vue
  components/HotNewsBanner.vue
  components/NavigationDropdown.vue
  components/NewsItemCard.vue
  components/NewsItemPost.vue
  components/OrganizationNav.vue
  components/slices/ActionsZone.vue
  components/slices/Article.vue
  components/slices/Features.vue
  components/slices/NavigationZone.vue
  components/slices/PageSection.vue
  components/slices/PartnersLogos.vue
  components/slices/PopInCampaigns.vue
  components/slices/Process.vue
  pages/pix-pro/digital-mediation.vue
  pages/pix-pro/employers.vue
  pages/pix-site/about.vue
  pages/pix-site/index.vue
  pages/pix-site/legal-notices.vue
  pages/pix-site/school-education.vue
  pages/pix-site/skills.vue
  pages/pix-site/stats.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#193 [FEATURE] Création du bloc Statistiques et refacto (PIX-1200).
  assets/scss/components/slices/features.scss
  assets/scss/components/slices/process.scss
  assets/scss/components/slices/statistics.scss
  components/SliceZone.vue
  components/slices/MultipleBlock.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#204 [FEATURE] Préciser le domaine Pix ou Pix pro dans les titres (PIX-1233).
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-pro/_custom-page.vue
  pages/pix-site/_custom-page.vue
  pages/pix-site/news/_slug.vue
Labels: Tech Review Needed, team-evaluation

#202 [FEATURE] Refonte footer (PIX-1298).
  components/AboutNav.vue
  components/AppFooter.vue
  components/FooterSliceZone.vue
  components/ResourcesNav.vue
  components/slices/Features.vue
  components/slices/NavigationGroup.vue
  layouts/default.vue
  plugins/i18n.js
  services/document-fetcher.js
  store/index.js
Labels: Func Review Needed, Tech Review OK, team-evaluation

#203 [FEATURE] Afficher les dernières actualités (PIX-1201).
  components/NewsItemCard.vue
  components/SliceZone.vue
  components/slices/LatestNews.vue
  pages/pix-site/_custom-page.vue
  pages/pix-site/index.vue
  pages/pix-site/news/index.vue
  tests/pages/pix-site/index.test.js
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#208 [CLEANUP] Correction de contraste
  components/FooterSliceZone.vue
  components/NewsItemCard.vue
  components/slices/Article.vue
  components/slices/Features.vue
  components/slices/NavigationGroup.vue
  components/slices/PageBanner.vue
Labels: Tech Review Needed
