Repository 1024pix/pix-site, pull requests merged in 2020-08, with the labels that each got.

#129 [FEATURE] Refonte du site vitrine: bannière sur la page d'accueil (PIX-1007)
  .gitignore
  assets/scss/globals/_breakpoints.scss
  assets/scss/globals/_colors.scss
  components/slices/banner.vue
  components/slices/hero-banner.vue
  config/breakpoints.js
  nuxt.config.js
  pages/index.vue
  pages/verify-certification-score.vue
  tests/pages/__snapshots__/index.test.js.snap
Labels: Design Review OK, Tech Review OK, team-certif, team-evaluation

#131 [FEATURE] Traduction de contenu hors PRISMIC (PIX-1073).
  components/app-footer.vue
  components/header-nav.vue
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/about.vue
  pages/formable-pages/contact-digital-mediation.vue
  pages/formable-pages/higher-education-establishment-registration.vue
  pages/formable-pages/pix-certification-application.vue
  pages/formable-pages/pix-orga-higher-school-registration.vue
  pages/formable-pages/pix-orga-registration.vue
  pages/higher-education.vue
  pages/index.vue
  pages/legal-notices.vue
  pages/news/index.vue
  pages/preview.vue
  pages/school-education.vue
  pages/skills.vue
  pages/stats.vue
  pages/terms-of-service.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#132 [FEATURE] Ré-implémenter le sélecteur de langues (PIX-1079).
  README.md
  components/language-dropdown.vue
  components/organization-nav.vue
  config/locale-domains.js
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  middleware/current-page-path.js
  nuxt.config.js
  pages/_simple-page.vue
  services/get-host-from-request.js
  store/index.js
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#133 [TECH] Faire un lint --fix à chaque build
  nuxt.config.js
Labels: Tech Review Needed, team-evaluation

#130 [Refacto] Mettre le layout de Pix Site en grid
  assets/scss/app.scss
  assets/scss/globals/_buttons.scss
  assets/scss/globals/_colors.scss
  assets/scss/globals/_container.scss
  assets/scss/globals/_titles.scss
  components/slices/banner.vue
  config/breakpoints.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/verify-certification-score.vue
  tests/pages/__snapshots__/verify-certification-score.test.js.snap
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#135 [BUGFIX] Enlever la détection du langage du navigateur.
  nuxt.config.js
Labels: Tech Review Needed

#138 [BUGFIX] S'assurer de l'affichage du menu gris et du switch de langue selon les contextes (PIX-1144).
  components/organization-nav.vue
Labels: Tech Review Needed, team-evaluation

#139 [BUGFIX] Remettre le bon style pour les boutons (PIX-1142).
  assets/scss/components/_app-navbar.scss
  assets/scss/globals/_buttons.scss
  components/main-nav.vue
Labels: Tech Review Needed, team-evaluation

#140 [BUGFIX] Les liens en FR redirigeaient vers du FR-FR (PIX-1145).
  components/pix-link.vue
  pages/_simple-page.vue
  pages/about.vue
  pages/formable-pages/contact-digital-mediation.vue
  pages/formable-pages/higher-education-establishment-registration.vue
  pages/formable-pages/pix-certification-application.vue
  pages/formable-pages/pix-orga-higher-school-registration.vue
  pages/formable-pages/pix-orga-registration.vue
  pages/help.vue
  pages/higher-education.vue
  pages/legal-notices.vue
  pages/news/index.vue
  pages/school-education.vue
  pages/skills.vue
  pages/stats.vue
  pages/terms-of-service.vue
  pages/verify-certification-score.vue
Labels: Tech Review Needed, team-evaluation

#134 [FEATURE] Mettre à jour la page SCO (PIX-891).
  components/slices/banner.vue
  components/slices/section.vue
  pages/school-education.vue
  tests/pages/__snapshots__/about.test.js.snap
  tests/pages/__snapshots__/higher-eduction.test.js.snap
  tests/pages/__snapshots__/index.test.js.snap
  tests/pages/__snapshots__/legal-notices.test.js.snap
  tests/pages/__snapshots__/school-eduction.test.js.snap
  tests/pages/school-eduction.test.js
Labels: Tech Review Needed, team-acces

#142 [FEATURE] Refonte du site vitrine: bloc features (PIX-1026)
  components/slices/Features.vue
  components/slices/SliceZone.vue
  config/breakpoints.js
  tests/pages/__snapshots__/index.test.js.snap
  tests/pages/index.test.js
Labels: Func Review Needed, Tech Review OK, team-evaluation

#152 [FEATURE] Rendre la page index contribuable (PIX-1126)
  components/slices/SliceZone.vue
  pages/index.vue
Labels: Func Review OK, Tech Review OK, team-evaluation

#137 [FEATURE] Création du composant article (PIX-1025).
  assets/scss/app.scss
  assets/scss/globals/_container.scss
  assets/scss/globals/_fonts.scss
  components/CtaButton.vue
  components/slices/Article.vue
  components/slices/SliceZone.vue
  nuxt.config.js
  package.json
  pages/index.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation
