Repository 1024pix/pix-site, pull requests merged in 2020-06, with the labels that each got.

#120 [BUGFIX] Adapter la taille des icones de la home (PIX-742).
  pages/index.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#121 [BUGFIX] Le texte Pix Pro a un titre alors que ce n'en ait pas un (PIX-873).
  components/burger-menu-nav.vue
Labels: Func Review OK, Tech Review OK, team-evaluation

#123 [FEATURE] Ajouter des titres aux pages (PIX-905).
  pages/about.vue
  pages/formable-pages/contact-digital-mediation.vue
  pages/formable-pages/higher-education-establishment-registration.vue
  pages/formable-pages/pix-certification-application.vue
  pages/formable-pages/pix-orga-higher-school-registration.vue
  pages/formable-pages/pix-orga-registration.vue
  pages/higher-education.vue
  pages/index.vue
  pages/legal-notices.vue
  pages/news/index.vue
  pages/school-education.vue
  pages/skills.vue
  pages/stats.vue
  pages/terms-of-service.vue
Labels: Func Review OK, Tech Review Needed, team-evaluation

#122 [FEATURE] Ajouter l'attribut lang (PIX-833).
  nuxt.config.js
Labels: Tech Review Needed
