Repository 1024pix/pix-site, pull requests merged in 2020-02, with the labels that each got.

#100 [DOC] Mise à jour du cahier des charges février 2020 (PS-12)
  static/documents/Cahier_des_charges_des_centres_de_certification_Pix_(tous_publics_hors_scolaires)_-_version_actualisee.pdf
Labels: Ready To Merge, enhancement

#101 [FEATURE] Rajoute une entrée accueil dans la navigation (PS-11).
  assets/scss/components/_app-navbar.scss
  components/main-nav.vue
Labels: Tech Review asked

#102 [BUGFIX] Corrige le bug de superposition dans le burger menu (PS-19).
  components/burger-menu-nav.vue
Labels: Func Review OK, Tech Review asked

#103 [FEATURE] Ajout du style pour le lien vers pro.pix.fr (PS-14).
  assets/scss/components/_main-nav.scss
  assets/scss/globals/_colors.scss
  components/main-nav.vue
Labels: Func Review Needed, Tech Review asked

#104 [FEATURE] Changer le breakpoint pour l’affichage du burger menu (PS-13).
  assets/scss/components/_app-navbar.scss
  assets/scss/globals/_breakpoints.scss
  assets/scss/globals/_globals.scss
  components/burger-menu-nav.vue
  components/header-nav.vue
Labels: Func Review Needed, Tech Review asked

#105 [FEATURE] Ajout vidéo sur la home page (PS-18)
  components/slices/hero-banner.vue
  components/slices/video.vue
  nuxt.config.js
  package-lock.json
  package.json
  plugins/sweet-modal.js
  plugins/vue-plyr.js
Labels: Func Review OK, Tech Review OK

#106 [FEATURE] Add Pix Pro links in Pix Site burger menu (PS-23).
  components/burger-menu-nav.vue
  components/header-nav.vue
  store/index.js
Labels: Func Review OK, Tech Review asked

#107 [FEATURE] Rédirection des utilisateurs de la page médiation numérique vers Pix Pro (PS-25).
  middleware/seo.js
  nuxt.config.js
  pages/digital-mediation.vue
Labels: Func Review OK, Tech Review asked
