Repository 1024pix/pix-site, pull requests merged in 2020-07, with the labels that each got.

#125 [TECH] Ajour d'une action GitHub.
  .github/workflows/ci.yml
  components/header-nav.vue
  tests/services/document-fetcher.test.js
Labels: Tech Review Needed, team-acces, team-certif, team-evaluation, team-prescription

#124 [A11Y] Revoir la gestion des alt sur la page pix.fr (PIX-907)
  components/app-footer.vue
  components/header-nav.vue
  components/pop-in-campaigns.vue
Labels: Tech Review Needed, team-evaluation

#119 [FEATURE] Ajouter le logo de l'Unesco sur les site .org (PIX-703)
  components/app-footer.vue
  static/images/ministere-logo.svg
  static/images/pix-logo.svg
  static/images/unesco_logo.svg
Labels: Design Review OK, Tech Review Needed, team-evaluation

#128 Ajout de tests pour les Pages
  package-lock.json
  package.json
  pages/higher-education.vue
  tests/pages/__snapshots__/about.test.js.snap
  tests/pages/__snapshots__/higher-eduction.test.js.snap
  tests/pages/__snapshots__/index.test.js.snap
  tests/pages/__snapshots__/legal-notices.test.js.snap
  tests/pages/__snapshots__/school-eduction.test.js.snap
  tests/pages/__snapshots__/skills.test.js.snap
  tests/pages/__snapshots__/terms-of-servie.test.js.snap
  tests/pages/about.test.js
  tests/pages/higher-eduction.test.js
  tests/pages/index.test.js
  tests/pages/legal-notices.test.js
  tests/pages/school-eduction.test.js
  tests/pages/skills.test.js
  tests/pages/terms-of-servie.test.js
  tests/pages/utils.js
Labels: Tech Review Needed

#127 [FEATURE ] Formulaire verification certificat (Pix 949)
  assets/scss/globals/_colors.scss
  pages/_simple-page.vue
  pages/about.vue
  pages/higher-education.vue
  pages/index.vue
  pages/legal-notices.vue
  pages/news/_slug.vue
  pages/news/index.vue
  pages/preview.vue
  pages/school-education.vue
  pages/skills.vue
  pages/stats.vue
  pages/terms-of-service.vue
  pages/verify-certification-score.vue
  plugins/link-resolver.js
  services/document-fetcher.js
  tests/pages/__snapshots__/verify-certification-score.test.js.snap
  tests/pages/verify-certification-score.test.js
  tests/services/document-fetcher.test.js
Labels: Tech Review Needed, team-certif
