Repository 1024pix/pix-site, pull requests merged in 2020-11, with the labels that each got.

#206 [BUGFIX] Correction des tailles d'images et de titres du MultipleBlock-Features (PIX-1530).
  assets/scss/components/slices/features.scss
  assets/scss/components/slices/statistics.scss
Labels: Func Review Needed, Tech Review Needed, hacktoberfest-accepted, team-evaluation

#212 [CLEANUP] Renommage de la route Legal Notice
  pages/pix-site/legal-notices.vue
Labels: Tech Review Needed

#211 [CLEANUP] Supprimer la page "qui sommes nous" (PIX-1431).
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/about.vue
  services/document-fetcher.js
  tests/pages/pix-site/__snapshots__/about.test.js.snap
  tests/pages/pix-site/about.test.js
Labels: Tech Review Needed, team-evaluation

#207 [FEATURE] Ajouter les pages de formulaires contribuables (PIX-1508).
  components/FormPage.vue
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-pro/_custom-page.vue
  pages/pix-site/_custom-page.vue
  services/document-fetcher.js
  tests/services/document-fetcher.test.js
Labels: Func Review OK, Tech Review OK, cross-team, team-evaluation

#213 [CLEANUP] Supprimer la page "Enseignement Scolaire" (PIX-1432).
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/school-education.vue
  services/document-fetcher.js
  tests/pages/pix-site/__snapshots__/school-education.test.js.snap
  tests/pages/pix-site/school-education.test.js
Labels: Tech Review Needed, team-evaluation

#201 [FEATURE] Génération statique de pix-site
  .buildpacks
  .gitignore
  README.md
  components/LanguageDropdown.vue
  components/NavigationDropdown.vue
  components/OrganizationNav.vue
  components/PixLink.vue
  components/slices/NavigationZone.vue
  components/slices/PageBanner.vue
  components/slices/PageSection.vue
  docker-compose.yml
  middleware/current-page-path.js
  middleware/pix-pro/current-page-path.js
  middleware/pix-pro/redirect-to-external-link.js
  middleware/pix-site/current-page-path.js
  middleware/pix-site/redirect-to-external-link.js
  nuxt.config.js
  package.json
  pages/pix-pro/index.vue
  pages/pix-site/help.vue
  pages/pix-site/legal-notices.vue
  pages/pix-site/news/_slug.vue
  pages/pix-site/skills.vue
  pages/pix-site/stats.vue
  pages/pix-site/terms-of-service.vue
  servers.conf.erb
  store/index.js
  tests.sh
  tests/components/slices/NavigationZone.test.js
Labels: Func Review Needed, Tech Review Needed, cross-team

#216 [BUGFIX] Pages en Erreur 404 sur les sites .fr et .org (PIX-1611)
  components/PixLink.vue
  nuxt.config.js
  plugins/html-serializer.js
  plugins/link-resolver.js
  plugins/prismicLinks.js
Labels: Func Review Needed, Tech Review Needed, cross-team

#215 [FEATURE] Ajout de la possibilité de servir le site en mode SSR ou en mode statique.
  README.md
  nuxt.config.js
  package.json
  scripts/build.sh
  scripts/start.sh
Labels: Func Review Needed, Tech Review Needed, cross-team

#217 [CLEANUP] Suppression de l'ancienne page Médiation Numérique
  pages/pix-pro/digital-mediation.vue
  plugins/link-resolver.js
  services/document-fetcher.js
Labels: Tech Review Needed, team-evaluation

#218 [BUGFIX] La page index de pix-pro affiche l'ancienne page (PIX-1438)
  pages/pix-pro/index.vue
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, cross-team

#220 [TECH] Mettre à jour Node et les paquets Pix Site (PIX-1633).
  .github/workflows/ci.yml
  components/DropdownButton.vue
  components/FormablePage.vue
  components/slices/PageBanner.vue
  components/slices/PageSection.vue
  components/slices/Process.vue
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/pix-pro/_custom-page.vue
  pages/pix-pro/index.vue
  pages/pix-site/_custom-page.vue
  pages/pix-site/index.vue
  pages/pix-site/legal-notices.vue
  pages/pix-site/news/_slug.vue
  pages/pix-site/news/index.vue
  pages/pix-site/skills.vue
Labels: :rocket: Ready To Merge, cross-team, team-evaluation

#222 [CLEANUP] Suppression de la page CGU (PIX-1434).
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/terms-of-service.vue
  plugins/link-resolver.js
  services/document-fetcher.js
  tests/pages/pix-site/__snapshots__/terms-of-service.test.js.snap
  tests/pages/pix-site/terms-of-service.test.js
Labels: :eyes: Tech Review Needed, team-evaluation

#223 [CLEANUP] Suppression de la page Legal Notice
  components/SimplePage.vue
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/legal-notices.vue
  plugins/link-resolver.js
  services/document-fetcher.js
  tests/pages/pix-site/__snapshots__/legal-notices.test.js.snap
  tests/pages/pix-site/legal-notices.test.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#224 [FEATURE] Ajout d'un bloc Stat (PIX-1643).
  components/ChartSection.vue
  components/SliceZone.vue
  components/slices/Stat.vue
  pages/pix-site/stats.vue
  tests/components/slices/Stat.test.js
Labels: :eyes: Tech Review Needed, cross-team, team-evaluation

#225 [CLEANUP] Supprimer les Slices inutiles (PIX-1430).
  components/SliceZone.vue
  components/slices/Features.vue
  components/slices/HeroBanner.vue
  components/slices/ImgTextColumn.vue
  components/slices/KeyNumbers.vue
  components/slices/MultipleBlock.vue
  components/slices/MultipleColumn.vue
  components/slices/Process.vue
  components/slices/SectionColumn.vue
  components/slices/WebSnippet.vue
  pages/pix-site/index.vue
  services/document-fetcher.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, cross-team, team-evaluation

#226 [CLEANUP] Supprimer la page "Compétence" (PIX-1436).
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/skills.vue
  services/document-fetcher.js
  tests/pages/pix-site/__snapshots__/skills.test.js.snap
  tests/pages/pix-site/skills.test.js
Labels: :eyes: Tech Review Needed, cross-team, team-evaluation

#227 [CLEANUP] Supprimer l'ancienne nav et la sous-nav (PIX-1429).
  components/BurgerMenuNav.vue
  components/NavigationSliceZone.vue
  components/PixProSubNav.vue
  plugins/i18n.js
  plugins/link-resolver.js
  services/document-fetcher.js
  store/index.js
  tests/components/slices/NavigationSliceZone.test.js
  tests/services/document-fetcher.test.js
Labels: :eyes: Tech Review Needed, cross-team

#229 [BUGFIX] Pouvoir voir tout le texte en mode mobile (PIX-1714).
  layouts/default.vue
Labels: :eyes: Tech Review Needed, cross-team

#228 [FEATURE] Ajouter un ID sur les slices pour faire des liens dessus (PIX-1576).
  components/SliceZone.vue
  components/slices/Article.vue
  components/slices/LatestNews.vue
  components/slices/MultipleBlock.vue
  components/slices/PageBanner.vue
  components/slices/PartnersLogos.vue
  components/slices/PopInCampaigns.vue
  components/slices/Stat.vue
Labels: :eyes: Tech Review Needed, cross-team, team-evaluation

#230 [CLEANUP] Retirer les filtres pour les logos de la navigation (PIX-1428).
  components/slices/LogosZone.vue
  tests/components/slices/LogosZone.test.js
Labels: :eyes: Tech Review Needed, cross-team, team-evaluation
