Repository 1024pix/pix-site, pull requests merged in 2020-09, with the labels that each got.

#153 [BUGFIX] Forcer la langue française sur pix.fr.
  nuxt.config.js
Labels: Func Review Needed, Tech Review Needed

#154 [BUGFIX] Fix le titre et les bullets points de la liste du slice article (PIX-1190)
  components/slices/Article.vue
Labels: team-evaluation

#150 [BSR] Petit nettoyage de la rentrée des slices (PIX-1215).
  README.md
  components/MediaPlayer.vue
  components/NewsItemCard.vue
  components/NewsItemPost.vue
  components/SliceZone.vue
  components/slices/Features.vue
  components/slices/HeroBanner.vue
  components/slices/ImgTextColumn.vue
  components/slices/KeyNumbers.vue
  components/slices/PageBanner.vue
  components/slices/PageSection.vue
  components/slices/PopInCampaigns.vue
  components/slices/SectionColumn.vue
  pages/about.vue
  pages/higher-education.vue
  pages/index.vue
  pages/legal-notices.vue
  pages/news/index.vue
  pages/school-education.vue
  pages/skills.vue
  tests/pages/__snapshots__/about.test.js.snap
  tests/pages/__snapshots__/higher-education.test.js.snap
  tests/pages/__snapshots__/legal-notices.test.js.snap
  tests/pages/__snapshots__/school-education.test.js.snap
Labels: team-evaluation

#155 [FEATURE] Améliorer l'accessibilité de la navigation (PIX-1214).
  components/AboutNav.vue
  components/AppFooter.vue
  components/BurgerMenuNav.vue
  components/HeaderNav.vue
  components/ResourcesNav.vue
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  layouts/default.vue
Labels: team-evaluation

#158 [BSR] Changer le template de PR pour afficher le template de RA.
  .github/pull_request_template.md
Labels: team-evaluation

#157 [BSR] Appliquer les conventions de nommage Prismic.
  components/slices/Features.vue
  components/slices/PageBanner.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#159 [FEATURE] Ajouter une couleur d'arrière-plan aux nouveaux blocs (PIX-1194).
  components/slices/Article.vue
  components/slices/Features.vue
  components/slices/PageBanner.vue
Labels: Tech Review Needed, team-evaluation

#162 [BUGFIX] Élargir la barre de navigation (PIX-1203).
  assets/scss/components/_app-navbar.scss
  assets/scss/globals/_container.scss
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-evaluation

#160 [BUGFIX] Éviter les imports multiples de CSS (PIX-1227).
  assets/scss/app.scss
  assets/scss/globals.scss
  assets/scss/pages/_digital-mediation.scss
  assets/scss/pages/_formable-page.scss
  assets/scss/pages/_organization.scss
  assets/scss/shared.scss
  assets/scss/shared/_buttons.scss
  assets/scss/shared/_container.scss
  assets/scss/shared/_margins.scss
  assets/scss/shared/_normalize.scss
  assets/scss/shared/_pages.scss
  assets/scss/shared/_text.scss
  assets/scss/shared/_titles.scss
  components/BurgerMenuNav.vue
  components/FormablePage.vue
  components/NewsItemCard.vue
  components/NewsItemPost.vue
  components/slices/PageSection.vue
  components/slices/PopInCampaigns.vue
  nuxt.config.js
  pages/about.vue
  pages/higher-education.vue
  pages/index.vue
  pages/legal-notices.vue
  pages/news/index.vue
  pages/school-education.vue
  pages/skills.vue
  pages/stats.vue
Labels: Design Review Needed, Tech Review Needed, cross-team, team-evaluation

#161 [FEATURE] Ajouter un sélecteur de contraste pour le texte de la bannière (PIX-1225).
  assets/scss/globals/_colors.scss
  assets/scss/shared/_buttons.scss
  assets/scss/shared/_text.scss
  assets/scss/shared/_titles.scss
  components/slices/PageBanner.vue
Labels: Design Review Needed, Func Review Needed, Tech Review Needed, team-evaluation

#163 [BUGFIX] Fix les warnings console sur Firefox (PIX-1231)
  components/slices/Features.vue
Labels: Tech Review Needed, team-evaluation

#156 [FEATURE] Permettre de créer de nouvelles pages avec des slices sur Prismic (PIX-1169)
  components/SimplePage.vue
  pages/_custom-page.vue
  pages/_simple-page.vue
  services/document-fetcher.js
  tests/services/document-fetcher.test.js
Labels: :rocket: Ready To Merge, team-evaluation

#165 [BUGFIX] Problèmes d'affichage sur la page Enseignement Supérieur du site vitrine (PIX-1218).
  assets/scss/shared/_buttons.scss
  assets/scss/shared/_normalize.scss
  components/slices/Article.vue
  components/slices/PageBanner.vue
  pages/higher-education.vue
  tests/pages/__snapshots__/higher-education.test.js.snap
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#167 [BUGFIX] Ajuster l'alignement des titres d'articles (PIX-1286).
  components/slices/Article.vue
Labels: Func Review OK, Tech Review Needed, team-evaluation

#168 [FEATURE] Migrer les pages pro dans pix-site (PIX-1261)
  components/slices/HeroBanner.vue
  pages/digital-mediation.vue
  pages/employers.vue
Labels: Tech Review OK, team-evaluation, team-prescription

#170 [FEATURE] Faire des builds dédiés pour pix-site et pix-pro (PIX-1260)
  README.md
  components/AppFooter.vue
  components/HeaderNav.vue
  middleware/pix-pro/current-page-path.js
  middleware/pix-pro/redirect-to-external-link.js
  middleware/pix-pro/seo.js
  middleware/pix-site/current-page-path.js
  middleware/pix-site/redirect-to-external-link.js
  middleware/pix-site/seo.js
  nuxt.config.js
  package.json
  pages/pix-pro/_simple-page.vue
  pages/pix-pro/digital-mediation.vue
  pages/pix-pro/employers.vue
  pages/pix-site/_custom-page.vue
  pages/pix-site/about.vue
  pages/pix-site/formable-pages/contact-digital-mediation.vue
  pages/pix-site/formable-pages/higher-education-establishment-registration.vue
  pages/pix-site/formable-pages/pix-certification-application.vue
  pages/pix-site/formable-pages/pix-orga-higher-school-registration.vue
  pages/pix-site/formable-pages/pix-orga-registration.vue
  pages/pix-site/help.vue
  pages/pix-site/higher-education.vue
  pages/pix-site/index.vue
  pages/pix-site/legal-notices.vue
  pages/pix-site/news/_slug.vue
  pages/pix-site/news/index.vue
  pages/pix-site/school-education.vue
  pages/pix-site/skills.vue
  pages/pix-site/stats.vue
  pages/pix-site/terms-of-service.vue
  store/index.js
  tests/pages/pix-site/__snapshots__/about.test.js.snap
  tests/pages/pix-site/__snapshots__/higher-education.test.js.snap
  tests/pages/pix-site/__snapshots__/index.test.js.snap
  tests/pages/pix-site/__snapshots__/legal-notices.test.js.snap
  tests/pages/pix-site/__snapshots__/school-education.test.js.snap
  tests/pages/pix-site/__snapshots__/skills.test.js.snap
  tests/pages/pix-site/__snapshots__/terms-of-service.test.js.snap
  tests/pages/pix-site/about.test.js
  tests/pages/pix-site/higher-education.test.js
  tests/pages/pix-site/index.test.js
  tests/pages/pix-site/legal-notices.test.js
  tests/pages/pix-site/school-education.test.js
  tests/pages/pix-site/skills.test.js
  tests/pages/pix-site/terms-of-service.test.js
  tests/pages/pix-site/utils.js
Labels: Tech Review OK, team-evaluation, team-prescription

#172 [FEATURE] Corriger le style de la page employeur (PIX-1261)
  pages/pix-pro/employers.vue
Labels: Tech Review OK, team-evaluation, team-prescription

#171 [FEATURE] Corriger le style de la page mediation numérique (PIX-1261)
  pages/pix-pro/digital-mediation.vue
Labels: Tech Review OK, team-evaluation, team-prescription

#174 [BUGFIX] Correction visuelle sur Pix-site (PF-1271).
  components/CtaButton.vue
  components/slices/Article.vue
  components/slices/Features.vue
  package.json
Labels: team-evaluation

#173 [FEATURE] Deployer pix-pro sur les reviews app (PIX-1263)
  .github/pull_request_template.md
  README.md
  package.json
Labels: Tech Review Needed, team-evaluation, team-prescription

#166 [FEATURE] Implémentation de la nouvelle barre de navigation (PIX-1071).
  assets/scss/components/_app-navbar.scss
  assets/scss/components/_index.scss
  assets/scss/globals/_colors.scss
  assets/scss/shared/_text.scss
  components/BurgerMenuNav.vue
  components/HeaderNav.vue
  components/NavigationDropdown.vue
  components/NavigationSliceZone.vue
  components/OrganizationNav.vue
  components/slices/ActionsZone.vue
  components/slices/Features.vue
  components/slices/LogosZone.vue
  components/slices/NavigationZone.vue
  layouts/default.vue
  nuxt.config.js
  plugins/i18n.js
  services/document-fetcher.js
  store/index.js
  tests/components/slices/NavigationZone.test.js
Labels: Func Review Needed, Tech Review Needed, team-evaluation

#176 [CLEANUP] Ajout d'un component PixImage au dessus du PrismicImage (PIX-1323).
  components/PixImage.vue
  components/slices/Article.vue
  components/slices/Features.vue
  components/slices/ImgTextColumn.vue
  components/slices/LogosZone.vue
  components/slices/PageBanner.vue
  components/slices/PageSection.vue
  components/slices/SectionColumn.vue
  plugins/components.js
  tests/components/PixImage.test.js
Labels: cross-team, team-evaluation

#177 [FEATURE] Pouvoir avoir les slices Article en vertical (PIX-1197).
  components/slices/Article.vue
Labels: Func Review Needed, Tech Review Needed, team-evaluation
