Repository 1024pix/pix-site, pull requests merged in 2020-05, with the labels that each got.

#115 [FEATURE] Gestion de pix.org et pix.fr (PIX-629).
  README.md
  components/pix-link.vue
  config/locale-domains.js
  lang/fr.js
  middleware/current-page-path.js
  nuxt.config.js
  package-lock.json
  package.json
  plugins/link-resolver.js
  store/index.js
Labels: Func Review OK, Tech Review OK, team-evaluation

#116 [FEATURE] Afficher la marianne que pour le site franco-français (PIX-667).
  components/header-nav.vue
Labels: Tech Review OK, team-evaluation

#118 [FEATURE] Pouvoir afficher 6 éléments dans les items de la home (PIX-705).
  pages/index.vue
Labels: Func Review Needed, Tech Review asked, team-evaluation
