Repository 1024pix/pix-site, pull requests merged in 2020-12, with the labels that each got.

#233 [TECH] Montée de version des packages eslint, nuxt et autoprefixer
  package-lock.json
  package.json
Labels: cross-team

#232 [CLEANUP] Supprimer la page Statistiques (PIX-1435).
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/stats.vue
  services/document-fetcher.js
Labels: :eyes: Tech Review Needed, cross-team

#231 [CLEANUP] Utiliser une SlicePage pour l'index du site vitrine (PIX-1444).
  pages/pix-site/index.vue
  tests/pages/pix-site/index.test.js
Labels: :eyes: Tech Review Needed, cross-team, team-evaluation
