Repository 1024pix/pix-site, pull requests merged in 2021-07, with the labels that each got.

#279 [BUGFIX] Aligner les logos des partenaires sur un grand écran.
  components/slices/PartnersLogos.vue
Labels: :rocket: Ready to Merge

#280 [TECH] Mettre à jour les dépendances.
  nuxt.config.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge

#281 [TECH] Monter de version @nuxtjs/prismic
  nuxt.config.js
  package-lock.json
  package.json
  services/get-routes-to-generate.js
  tests/services/document-fetcher.test.js
  tests/services/get-routes-to-generate.test.js
Labels: :rocket: Ready to Merge

#283 [TECH] Suppression de l'appel à Google Font.
  assets/fonts/Open_Sans/italic-400.woff2
  assets/fonts/Open_Sans/normal-300.woff2
  assets/fonts/Open_Sans/normal-400.woff2
  assets/fonts/Open_Sans/normal-600.woff2
  assets/fonts/Open_Sans/normal-700.woff2
  assets/fonts/Roboto/normal-400.woff2
  assets/fonts/Roboto/normal-500.woff2
  assets/scss/globals.scss
  assets/scss/globals/_fonts.scss
  assets/scss/globals/_google-font.scss
  nuxt.config.js
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#278 [TECH] Utiliser l'auto-import des composants proposé par Nuxt.
  components/BurgerMenuNav.vue
  components/ChartSection.vue
  components/FooterSliceZone.vue
  components/NavigationSliceZone.vue
  components/NewsItemPost.vue
  components/SliceZone.vue
  components/slices/ActionsZone.vue
  components/slices/Article.vue
  components/slices/LatestNews.vue
  components/slices/NavigationZone.vue
  components/slices/PageBanner.vue
  components/slices/Stat.vue
  layouts/default.vue
  nuxt.config.js
  pages/pix-pro/_custom-page.vue
  pages/pix-pro/index.vue
  pages/pix-site/_custom-page.vue
  pages/pix-site/index.vue
  pages/pix-site/news/_slug.vue
  pages/pix-site/news/index.vue
  tests/components/slices/NavigationSliceZone.test.js
  tests/components/slices/NavigationZone.test.js
  tests/pages/pix-site/index.test.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#282 [FEAT] Ajout de Matomo à Pix Pro (PIX-2800).
  nuxt.config.js
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team

#284 [BUGFIX] Afficher correctement le bloc statistiques sur un grand écran.
  assets/scss/components/slices/statistics.scss
Labels: :rocket: Ready to Merge, Tech Review OK

#285 [TECH] Mise à jour de Jest vers la 27.0.6
  jest.config.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK

#286 [TECH] Utilise l'option modern du module prismic pour éviter un appel vers prismic sur la prod
  nuxt.config.js
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge

#287 [BUGFIX] Centrer les articles verticaux.
  components/slices/Article.vue
Labels: :rocket: Ready to Merge, Tech Review OK
