Repository 1024pix/pix-site, pull requests merged in 2021-08, with the labels that each got.

#288 [FEATURE] Créer à chaque déploiement les graphiques de statistiques (PIX-2919).
  README.md
  components/slices/Stat.vue
  modules/propagate-fetch-error-during-generation.js
  nuxt.config.js
  package-lock.json
  package.json
  services/metabase-fetcher.js
  tests/components/slices/Stat.test.js
  tests/services/metabase-fetcher.test.js
Labels: :rocket: Ready to Merge, cross-team

#290 [FEATURE] Ajout du tag manager sur le site vitrine.
  README.md
  nuxt.config.js
  static/scripts/start-matomo-event.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#292 [TECH] Met à jour prismic-dom vers la version 2.2.6
  package-lock.json
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge

#291 [BUGFIX] Correction de l'affichage sur les écrans large (PIX-2764).
  assets/scss/components/slices/process.scss
  components/FooterSliceZone.vue
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#293 Utilise support.pix.org plutôt que support.pix.fr
  servers.conf.erb
  tests.sh
Labels: :eyes: Tech Review Needed, :eyes: Func Review Needed, :rocket: Ready to Merge
