Repository 1024pix/pix-site, pull requests merged in 2021-12, with the labels that each got.

#336 [TECH] Nettoyage document fetcher (PIX-3929, PIX-3932)
  components/FooterSliceZone.vue
  components/HotNewsBanner.vue
  components/NavigationSliceZone.vue
  pages/pix-pro/_custom-page.vue
  pages/pix-pro/index.vue
  pages/pix-site/_custom-page.vue
  plugins/link-resolver.js
  services/document-fetcher.js
  services/get-routes-to-generate.js
  tests/components/slices/NavigationSliceZone.test.js
  tests/pages/pix-site/index.test.js
  tests/services/document-fetcher.test.js
  tests/services/get-routes-to-generate.test.js
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#327 [TECH] Migration vers @nuxt/image (PIX-3945)
  assets/scss/components/slices/features.scss
  assets/scss/components/slices/process.scss
  assets/scss/components/slices/statistics.scss
  components/FooterSliceZone.vue
  components/NavigationSliceZone.vue
  components/PixImage.vue
  components/slices/Article.vue
  components/slices/LogosZone.vue
  components/slices/MultipleBlock.vue
  components/slices/PageBanner.vue
  components/slices/PartnersLogos.vue
  nuxt.config.js
  package-lock.json
  package.json
  tests/components/PixImage.test.js
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#339 [BUGFIX] Utilisation d'unités relatives pour les colonnes de features
  assets/scss/components/slices/features.scss
Labels: :rocket: Ready to Merge, team-evaluation

#340 [BUGFIX] Ajout de roles sémantiques dans les balises html (PIX-3999)
  components/NavigationSliceZone.vue
  components/slices/NavigationZone.vue
  layouts/default.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#341 [BUGFIX] Lance Prettier sur les fichiers SCSS (PIX-4010)
  assets/scss/components/_app-header.scss
  assets/scss/components/_index.scss
  assets/scss/components/_main-nav.scss
  assets/scss/components/slices/features.scss
  assets/scss/components/slices/process.scss
  assets/scss/components/slices/statistics.scss
  assets/scss/globals.scss
  assets/scss/globals/_breakpoints.scss
  assets/scss/globals/_colors.scss
  assets/scss/globals/_google-font.scss
  assets/scss/shared.scss
  assets/scss/shared/_buttons.scss
  assets/scss/shared/_margins.scss
  assets/scss/shared/_normalize.scss
  assets/scss/shared/_text.scss
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#342 [TECH] Supprime le dossier `store` qui était inutilisé (PIX-4011)
  store/README.md
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#344 [BUGFIX] Boucle infinie Nginx sur les 404 pix.org
  servers.conf.erb
Labels: :rocket: Ready to Merge, team-evaluation, cross-team, team-captains

#347 [BUGFIX] Logo Pix qui bouge selon les environnements (PIX-3927)
  components/FooterSliceZone.vue
Labels: team-evaluation, :eyes: Design Review Needed

#348 [FEATURE] Ajouter le langage 'FR-BE' dans pix-site (PIX-4035)
  components/PixLink.vue
  lang/fr-be.js
  nuxt.config.js
  pages/pix-site/_custom-page.vue
  pages/pix-site/index.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation
