Repository 1024pix/pix-site, pull requests merged in 2021-05, with the labels that each got.

#263 [TECH] Amélioration du focus des boutons (PIX-2534).
  assets/scss/globals/_colors.scss
  assets/scss/shared/_buttons.scss
  components/CtaButton.vue
  components/MainNav.vue
  components/slices/PageBanner.vue
  components/slices/PopInCampaigns.vue
Labels: :rocket: Ready to Merge, cross-team, team-evaluation

#265 [FEATURE] Changer la police des titres (PIX-2268).
  layouts/default.vue
Labels: :eyes: Design Review Needed, :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#266 [FEATURE] Changer les specs de la font (PIX-2269).
  assets/scss/components/slices/features.scss
Labels: :rocket: Ready to Merge, team-evaluation

#267 [BUGFIX] Fix affichage du favicon sur le site .org (PIX-2351).
  servers.conf.erb
  tests.sh
Labels: :rocket: Ready to Merge, team-evaluation

#269 [TECH] Expliciter les règles utilisées par le hook de merge Github pour agir dans JIRA (PIX-2586).
  .github/workflows/on-dev-merge.yml
Labels: Tech Review OK, cross-team
