Repository 1024pix/pix-site, pull requests merged in 2021-01, with the labels that each got.

#235 [TECH] Désactiver la prévisualisation de Prismic quand le mode SSR n'est pas activé.
  nuxt.config.js
Labels: :eyes: Tech Review Needed, cross-team

#237 [BUGFIX] Afficher le titre de la page en title (PIX-2028).
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/index.vue
  tests/pages/pix-site/index.test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, team-evaluation

#238 [BUGFIX] Rendre visible le burger menu en cas de message (PIX-1960).
  components/BurgerMenuNav.vue
  components/HotNewsBanner.vue
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, cross-team, team-evaluation
