Repository 1024pix/pix-site, pull requests merged in 2021-02, with the labels that each got.

#239 [FEATURE] Affichage du changement de langue sur pix.org (PIX-1601).
  components/BurgerMenuNav.vue
  components/DropdownButton.vue
  components/LanguageDropdown.vue
  components/LanguageSwitcher.vue
  components/NavigationSliceZone.vue
  components/OrganizationNav.vue
  components/slices/ActionsZone.vue
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  static/images/globe-blue.svg
  static/images/globe.svg
Labels: :eyes: Tech Review Needed, Func Review OK, team-evaluation

#241 [BUILD] Add build module to extract assets (images, videos, pdf) in final bundle
  jest.config.js
  modules/assets-extractor.js
  modules/save-remote-asset.js
  nuxt.config.js
  package-lock.json
  package.json
  scripts/start.sh
  tests/modules/assets-extractor.test.js
Labels: Func Review OK, Tech Review OK

#243 [FEATURE] Changement de design du language switcher (PIX-2216).
  components/LanguageSwitcher.vue
  static/images/globe.svg
Labels: :rocket: Ready To Merge, Tech Review OK, team-evaluation

#244 [FIX] Désactiver l'extraction des images pour qu'elles s'affichent sur les site .org
  nuxt.config.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, cross-team

#245 [TECH] Ajouter le workflow d'automatisation des merges.
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready To Merge, team-evaluation

#242 [TECH] Bumper les paquets (PIX-2215).
  .eslintrc.js
  package-lock.json
  package.json
  tests/components/PixImage.test.js
Labels: :rocket: Ready to Merge, cross-team
