Repository 1024pix/pix-site, pull requests merged in 2021-11, with the labels that each got.

#313 [TECH] Mettre à jour le package @nuxtjs/i18n
  nuxt.config.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge

#317 [BUGFIX] Affichage de la vidéo au scroll sur la page d'accueil
  components/slices/PageBanner.vue
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#306 [TECH] Mettre à jour les dépendances
  .eslintrc.js
  package-lock.json
  package.json
  tests/services/get-routes-to-generate.test.js
Labels: :rocket: Ready to Merge, cross-team

#319 [BUGFIX] Retirer le texte des actions de la barre de navigation sur mobile.
  components/BurgerMenuNav.vue
  components/NavigationSliceZone.vue
  components/slices/ActionsZone.vue
  components/slices/LogosZone.vue
Labels: :rocket: Ready to Merge, cross-team

#305 [INFRA] Utilise seulement le mode static de Nuxt
  README.md
  nuxt.config.js
  package.json
  scripts/build.sh
Labels: :rocket: Ready to Merge, cross-team

#314 [BUGFIX] a11y - Ordre des headers de la page d'actualités
  components/NewsItemCard.vue
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#320 [TECH] Supprimer le store Vuex (PIX-1468).
  components/FooterSliceZone.vue
  components/HotNewsBanner.vue
  components/NavigationSliceZone.vue
  store/index.js
  tests/components/slices/NavigationSliceZone.test.js
Labels: :rocket: Ready to Merge, team-evaluation

#318 [BUGFIX] Redirections Nginx
  servers.conf.erb
  tests.sh
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#324 [INFRA] Mise à jour de node de 14.16.0 à 14.17.0
  .nvmrc
  package.json
Labels: :rocket: Ready to Merge, cross-team, dependencies

#312 [BUGFIX] Amélioration de l'auto-merge.
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge, cross-team

#328 [FEATURE] Corriger les titles pour les actualités.
  assets/scss/shared/_text.scss
  components/NewsItemCard.vue
  lang/en-gb.js
  lang/fr-fr.js
  lang/fr.js
  pages/pix-site/news/index.vue
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#333 [INFRA] Mettre en cache les contenus des dossiers `images` et `scripts`
  servers.conf.erb
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#334 [TECH] Utilise le PIX_SERVICE_ACTIONS_TOKEN dans l'action d'automerge
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#325 [BUGFIX] Ajoute les attributs `width` et `height` aux icônes
  components/FooterSliceZone.vue
  components/slices/LogosZone.vue
Labels: :rocket: Ready to Merge, team-evaluation, cross-team

#335 [BUGFIX] Correction logo pix-pro
  components/slices/LogosZone.vue
Labels: :rocket: Ready to Merge, team-evaluation

#337 [TECH] Les pages en erreur renvoient une erreur Nginx
  nuxt.config.js
  servers.conf.erb
Labels: :rocket: Ready to Merge, team-evaluation, cross-team
