Repository 1024pix/pix-site, pull requests merged in 2021-04, with the labels that each got.

#260 [CLEANUP] Correctif d'accessibilité (PIX-2459).
  assets/scss/components/slices/features.scss
  assets/scss/globals/_colors.scss
  assets/scss/shared/_buttons.scss
  components/FooterSliceZone.vue
  components/NavigationSliceZone.vue
  components/slices/ActionsZone.vue
  components/slices/NavigationZone.vue
Labels: Tech Review OK, cross-team, team-evaluation

#261 [BUGFIX] Accéder aux pages orphelines (PIX-2487).
  services/get-routes-to-generate.js
  tests/services/get-routes-to-generate.test.js
Labels: :rocket: Ready to Merge, cross-team

#262 [TECH] Faire échouer le build quand la génération d'une page statique est en erreur
  package.json
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team
