Repository 1024pix/pix-site, pull requests merged in 2021-03, with the labels that each got.

#247 [FEATURE] Ne plus bouger les icone quand on ouvre le burger menu (PIX-2242).
  components/LanguageSwitcher.vue
  components/NavigationSliceZone.vue
  layouts/error.vue
  tests/components/slices/NavigationSliceZone.test.js
Labels: :rocket: Ready to Merge, team-evaluation

#246 [FEATURE] Générer les pages "orphelines" (PIX-2246).
  nuxt.config.js
  services/get-routes-to-generate.js
  tests/services/get-routes-to-generate.test.js
Labels: :eyes: Func Review Needed, :eyes: Tech Review Needed, :rocket: Ready to Merge, team-evaluation

#248 [DESIGN] Ajouter un arrondi sur les bannières de pages (PIX-2245).
  components/slices/PageBanner.vue
Labels: :rocket: Ready to Merge, Design Review OK, Tech Review OK, team-evaluation

#249 [FEATURE] Redesign du menu burger (PIX-2257).
  components/BurgerMenuNav.vue
  components/BurgerMenuNavItems.vue
  components/NavigationSliceZone.vue
  components/slices/ActionsZone.vue
Labels: Func Review OK, Tech Review OK, team-evaluation

#250 Activer l'asset-extractor et corriger l'affichage d'image sur pix.org
  nuxt.config.js
  scripts/signal_deploy_to_pr.sh
  servers.conf.erb
  tests.sh
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, cross-team

#252 [DESIGN] Changer la position du drop-down ouvert (PIX-2240).
  components/NavigationDropdown.vue
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#253 [DESIGN] Changer les specs de la font du drop-down (PIX-2239)
  components/NavigationDropdown.vue
Labels: :rocket: Ready to Merge, Design Review OK, Func Review OK, team-evaluation

#256 [DESIGN] Changer la marge au niveau des logo (PIX-2236).
  components/slices/LogosZone.vue
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#255 [BUGFIX] Corriger l'affichage du language switcher (PIX-2317).
  components/LanguageSwitcher.vue
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#257 [DESIGN] Modification des barres verticales sur le menu (PIX-2232).
  components/slices/NavigationZone.vue
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#258 [FEATURE] Modifier les margins et paddings pour pouvoir mieux agrandir le menu (PIX-2347).
  components/NavigationSliceZone.vue
  components/slices/ActionsZone.vue
  components/slices/NavigationZone.vue
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#259 [FEATURE] Changement de couleur des labels de navigation (PIX-2233).
  components/LanguageSwitcher.vue
  components/NavigationDropdown.vue
  components/slices/ActionsZone.vue
  components/slices/NavigationZone.vue
Labels: :rocket: Ready to Merge, Func Review OK, Tech Review OK, team-evaluation
