Repository 1024pix/pix-site, pull requests merged in 2021-06, with the labels that each got.

#271 [TECH] Lire l'URL Matomo dans l'environnement
  nuxt.config.js
Labels: :eyes: Tech Review Needed

#272 Activer ou désactiver les analytics
  README.md
  nuxt.config.js
Labels: :eyes: Tech Review Needed

#273 [CLEAN] Suppression des anciennes pages de formulaires (PIX-1441).
  components/FormablePage.vue
  pages/pix-site/formable-pages/contact-digital-mediation.vue
  pages/pix-site/formable-pages/higher-education-establishment-registration.vue
  pages/pix-site/formable-pages/pix-certification-application.vue
  pages/pix-site/formable-pages/pix-orga-higher-school-registration.vue
  pages/pix-site/formable-pages/pix-orga-registration.vue
Labels: :rocket: Ready to Merge, cross-team

#275 [FEATURE] Ajouter un état actif au éléments de la navigation (PIX-2235).
  components/PixLink.vue
  components/slices/NavigationZone.vue
  tests/components/slices/NavigationZone.test.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-evaluation

#274 Expliciter la différence entre les hotnews et le reste du site
  components/HotNewsBanner.vue
Labels: :rocket: Ready to Merge, cross-team
