Repository 1024pix/pix-site, pull requests merged in 2022-12, with the labels that each got.

#427 [TECH] Supprime les conditions d'affichage du `LanguageSwitcher` (PIX-6480)
  components/BurgerMenuNav.vue
  components/LanguageSwitcher/LanguageSwitcher.vue
  components/slices/ActionsZone.vue
  config/environment.js
  nuxt.config.js
  sample.env
  tests/components/BurgerMenuNav.test.js
  tests/components/LanguageSwitcher.test.js
  tests/components/slices/ActionsZone.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#429 [TECH] Supprimer le workflow qui transitionne les tickets JIRA.
  .github/workflows/on-dev-merge.yml
Labels: Tech Review OK, :rocket: Ready to Merge

#432 [TECH] Permettre d'utiliser une version plus récente de npm
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge

#439 [FEATURE] Utiliser la bonne valeur d'attribut `lang` sur la balise `html` (PIX-6520)
  layouts/default.vue
  layouts/error.vue
  nuxt.config.js
  tests/layouts/default.test.js
  tests/layouts/error.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#438 [TECH] Migrer de moment à dayjs
  components/NewsItemCard.vue
  components/NewsItemPost.vue
  nuxt.config.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, team-evaluation

#441 [TECH] Améliorer la lisibilité des configurations des modules
  nuxt.config.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#440 [TECH] Simplifier la lecture des configurations i18n en fonction du domaine.
  config/environment.js
  nuxt.config.js
  services/is-seo-indexing-enabled.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#443 [TECH] Relaxe les versions de Node.js et npm (PIX-6574)
  .circleci/config.yml
  .nvmrc
  package-lock.json
  package.json
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#446 [BUGFIX] Corriger l'affichage des icônes (PIX-6602).
  nuxt.config.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge

#444 [TECH] Améliorer la lisibilité de la configuration des locales.
  config/language/pix-pro.js
  config/language/pix-site.js
  nuxt.config.js
  services/get-routes-to-generate.js
  tests/config/language/pix-pro.test.js
  tests/config/language/pix-site.test.js
  tests/services/get-routes-to-generate.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#450 [TECH] Supprimer le template de pull request
  .github/pull_request_template.md
Labels: Tech Review OK, :rocket: Ready to Merge

#447 [TECH] Migrer de nuxt-fontawesome à @nuxtjs/fontawesome
  nuxt.config.js
  package-lock.json
  package.json
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#448 [TECH] Suppression de warnings au `npm ci`
  .eslintrc.js
  components/slices/ActionsZone.vue
  components/slices/Article.vue
  components/slices/LatestNews.vue
  components/slices/LogosZone.vue
  components/slices/MultipleBlock.vue
  components/slices/NavigationGroup.vue
  components/slices/NavigationZone.vue
  components/slices/PageBanner.vue
  components/slices/PageSection.vue
  components/slices/PartnersLogos.vue
  components/slices/Stat.vue
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#442 [TECH] Ajouter des tests sur le language switcher
  tests/components/LanguageSwitcher.test.js
  tests/components/__snapshots__/LanguageSwitcher.test.js.snap
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#449 [TECH] Refactorer le language switcher (PIX-6604).
  components/LanguageSwitcher/LanguageSwitcher.vue
  components/LanguageSwitcher/LanguageSwitcherSubMenu.vue
  config/environment.js
  config/language/pix-pro.js
  config/language/pix-site.js
  services/get-absolute-url-if-switch-website.js
  services/use-get-absolute-url-if-switch-website.js
  tests/components/LanguageSwitcher.test.js
  tests/components/__snapshots__/LanguageSwitcher.test.js.snap
  tests/config/language/pix-pro.test.js
  tests/config/language/pix-site.test.js
  tests/services/get-absolute-url-if-switch-website.test.js
  tests/services/use-get-absolute-url-if-switch-website.test.js
Labels: :rocket: Ready to Merge, team-evaluation, team-acces

#452 [TECH] Ne plus ajouter de lien vers la review-app dans la pull-request
  package.json
  scripts/signal_deploy_to_pr.sh
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#445 [FEATURE] Ajouter une page d'accueil proposant à l'utilisateur de choisir sa langue (PIX-6433).
  assets/scss/globals/_colors.scss
  components/BurgerMenuNavItems.vue
  components/CtaButton.vue
  components/FooterSliceZone.vue
  components/LocaleLink.vue
  components/MainNav.vue
  components/NavigationDropdown.vue
  components/PixPrismicLink.vue
  components/slices/ActionsZone.vue
  components/slices/Article.vue
  components/slices/LatestNews.vue
  components/slices/LogosZone.vue
  components/slices/NavigationGroup.vue
  components/slices/NavigationZone.vue
  components/slices/PageBanner.vue
  components/slices/PageSection.vue
  config/language/pix-site.js
  layouts/home.vue
  nuxt.config.js
  pages/pix-site/locale-choice.vue
  plugins/components.js
  services/get-absolute-url-if-switch-website.js
  static/images/logo-pix-blanc.svg
  static/images/planet.svg
  static/images/stars.svg
  tests/components/PixPrismicLink.test.js
  tests/components/slices/ActionsZone.test.js
  tests/components/slices/NavigationZone.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces
