Repository 1024pix/pix-site, pull requests merged in 2022-03, with the labels that each got.

#375 [BUGFIX] Redirige les pages localisées de pix.fr vers pix.org (PIX-4496)
  servers.conf.erb
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-captains

#376 [BUGFIX] Bloquer l'indexation Google des liens dépréciés
  servers.conf.erb
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-captains

#377 [TECH] Correction tests NGINX
  README.md
  tests.sh
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#373 [TECH] Améliorer la propreté du code
  app/prismic/html-serializer.js
  app/prismic/link-resolver.js
  assets/scss/components/slices/features.scss
  assets/scss/shared/_buttons.scss
  components/LanguageSwitcher.vue
  components/LanguageSwitcherLegacy.vue
  components/NewsItemCard.vue
  lang/en-gb.js
  lang/fr-be.js
  lang/fr-fr.js
  lang/fr.js
  nuxt.config.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#378 [FEATURE] Ne cache pas la donnée au click sur la légende d'un graphique
  components/LineChart.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#379 [BUGFIX] Traduction page d'erreur et liens localisés
  lang/en-gb.js
  lang/fr-be.js
  lang/fr-fr.js
  lang/fr.js
  layouts/error.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#381 [BUGFIX] Utilise nuxt/image sur toute les images
  components/NewsItemCard.vue
  components/slices/Article.vue
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team
