Repository 1024pix/pix-site, pull requests merged in 2022-05, with the labels that each got.

#380 [TECH] Utiliser la nouvelle version LTS de node 16.14.0
  .circleci/config.yml
  .nvmrc
  package-lock.json
  package.json
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, cross-team, team-captains

#392 [TECH] Supprimer les types de document Prismic inutiles (PIX-4895).
  app/prismic/link-resolver.js
  services/document-fetcher.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#393 [FEATURE] Renvoyer vers les bonnes locales quand les pages de prismic référencent des liens vers d'autres pages (PIX-4903).
  app/prismic/link-resolver.js
  lang/en-gb.js
  lang/fr-be.js
  lang/fr-fr.js
  lang/fr.js
  lang/index.js
  tests/app/prismic/link-resolver.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#394 [TECH] Utilisation du tag index dans le link-resolver.
  app/prismic/link-resolver.js
  services/document-fetcher.js
  tests/app/prismic/link-resolver.test.js
  tests/pages/pix-site/index.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#395 [FEATURE] Générer les pages des sites en fonctions des tags Prismic (PIX-4905).
  app/prismic/link-resolver.js
  jest.config.js
  nuxt.config.js
  services/get-routes-to-generate.js
  services/link-resolver.js
  setEnvVars.js
  tests/services/get-routes-to-generate.test.js
  tests/services/link-resolver.test.js
  tests/services/metabase-fetcher.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#401 [BUGFIX] Répare l'environnement de dev
  components/NewsItemPost.vue
  components/PrismicCustomSliceZone.vue
  package-lock.json
  package.json
  pages/pix-pro/_custom-page.vue
  pages/pix-pro/index.vue
  pages/pix-site/_custom-page.vue
  pages/pix-site/index.vue
  tests/pages/pix-site/__snapshots__/index.test.js.snap
  tests/pages/pix-site/index.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#398 [FEATURE] Générer les routes en fonctions de la variable SITE_DOMAIN (fr,org) (PIX-4807).
  components/PixLink.vue
  config/environment.js
  config/language.js
  docker-compose.yml
  nuxt.config.js
  package.json
  sample.env
  servers.conf.erb
  services/get-routes-to-generate.js
  setEnvVars.js
  tests.sh
  tests/components/PixLink.test.js
  tests/config/language.test.js
  tests/services/get-routes-to-generate.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#403 [TECH] Accéder au domaine .org sur les RA (PIX-4963).
  servers.conf.erb
  tests.sh
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#400 [FEATURE] Ajout d'un FT pour l'affichage du Language-Switcher dans pro.pix.org (PIX-4934).
  components/BurgerMenuNav.vue
  components/slices/ActionsZone.vue
  config/environment.js
  sample.env
  tests/components/BurgerMenuNav.test.js
  tests/components/__snapshots__/BurgerMenuNav.test.js.snap
  tests/components/slices/ActionsZone.test.js
  tests/components/slices/__snapshots__/ActionsZone.test.js.snap
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#405 [FEATURE] Ajout du switch de langues sur Pix Pro (PIX-4808).
  components/LanguageSwitcher/LanguageSwitcher.vue
  components/LanguageSwitcher/LanguageSwitcherSubMenu.vue
  config/language/index.js
  config/language/pix-pro.js
  config/language/pix-site.js
  jest.config.js
  services/get-routes-to-generate.js
  services/use-get-absolute-url-if-switch-website.js
  setEnvVars.js
  tests/components/LanguageSwitcher.test.js
  tests/config/language.test.js
  tests/config/language/index.test.js
  tests/config/language/pix-pro.test.js
  tests/config/language/pix-site.test.js
  tests/services/get-routes-to-generate.test.js
  tests/services/metabase-fetcher.test.js
  tests/services/use-get-absolute-url-if-switch-website.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge
