Repository 1024pix/pix-site, pull requests merged in 2022-01, with the labels that each got.

#346 [BUGFIX] Laisse Google indexer le site seulement si `SEO_ENABLE_INDEXING` est settée à `true` (PIX-4040)
  nuxt.config.js
  package-lock.json
  package.json
  services/is-seo-indexing-enabled.js
  static/README.md
  static/robots.txt
Labels: :rocket: Ready to Merge, team-evaluation, cross-team, team-captains

#345 [BUGFIX] Éviter les redirections permanentes sur des liens qui peuvent changer
  servers.conf.erb
Labels: :rocket: Ready to Merge, cross-team, team-captains

#343 [TECH] Meilleure gestion de la var d'env `SITE` (PIX-4014)
  components/FooterSliceZone.vue
  components/LanguageSwitcher.vue
  components/NavigationSliceZone.vue
  components/PixLink.vue
  middleware/current-page-path.js
  nuxt.config.js
  package.json
  services/available-sites.js
  services/document-fetcher.js
  services/get-routes-to-generate.js
  tests/components/slices/NavigationSliceZone.test.js
  tests/services/document-fetcher.test.js
Labels: :rocket: Ready to Merge, team-evaluation

#351 [TECH] Utiliser la github action d'auto-merge commune de Pix
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge

#352 [TECH] Montée de version action d'auto-merge en v0.1.2
  .github/workflows/auto-merge.yml
Labels: :rocket: Ready to Merge

#349 [FEATURE] Ajouter le menu Switch de langue sur le .org (PIX-4038)
  components/LanguageSwitcher.vue
  components/LanguageSwitcherLegacy.vue
  config/language.js
  lang/en-gb.js
  lang/fr-be.js
  lang/fr-fr.js
  lang/fr.js
  nuxt.config.js
  pages/pix-site/news/_slug.vue
  pages/pix-site/news/index.vue
  static/images/flag-be.svg
  static/images/flag-fr.svg
  static/images/globe-europe.svg
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, Design Review OK

#353 [FEATURE] Ajout d'un Feature Toggle pour le switch de langue FR-BE (PIX-4101).
  components/BurgerMenuNav.vue
  components/LanguageSwitcher.vue
  components/LanguageSwitcherLegacy.vue
  components/PixLink.vue
  components/slices/ActionsZone.vue
  config/language.js
  lang/en-gb.js
  lang/fr.js
  nuxt.config.js
  pages/pix-site/_custom-page.vue
  pages/pix-site/index.vue
  pages/pix-site/news/_slug.vue
  pages/pix-site/news/index.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge

#355 [BUGFIX] Affichage de la bannière de nouveautés
  services/document-fetcher.js
  tests/services/document-fetcher.test.js
Labels: :rocket: Ready to Merge, team-evaluation

#356 [TECH] Ajoute un log pour afficher le nombre de routes générées
  .eslintrc.js
  nuxt.config.js
  pages/pix-site/index.vue
  pages/pix-site/news/_slug.vue
  pages/pix-site/news/index.vue
  services/get-routes-to-generate.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#357 [BUGFIX] Ne pas inclure les routes à générer si la langue n'est pas gérée (PIX-4173)
  services/get-routes-to-generate.js
  tests/services/get-routes-to-generate.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#360 [FIX] Correction des redirections vers le site belge renvoyant une page 404.
  nuxt.config.js
  plugins/i18n.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge

#363 [BUGFIX] Les URLs inter-locales ne fonctionnent pas correctement
  components/PixLink.vue
  tests/components/PixLink.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#358 [STYLE] Correctifs sur le switch de langue sur Pix.org (PIX-4133).
  components/LanguageSwitcher.vue
  components/LanguageSwitcherLegacy.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#362 [FEATURE] Supprime le feature toggle `IS_FR_BE_LANGUAGE_LOCALE_AVAILABLE`
  components/BurgerMenuNav.vue
  components/slices/ActionsZone.vue
  config/language.js
  lang/en-gb.js
  lang/fr.js
  nuxt.config.js
  pages/pix-site/_custom-page.vue
  pages/pix-site/index.vue
  pages/pix-site/news/_slug.vue
  pages/pix-site/news/index.vue
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation
