Repository 1024pix/pix-site, pull requests merged in 2023-06, with the labels that each got.

#541 [FEATURE] Ajout d'un bandeau de consentement le temps d'un audit
  components/ConsentBanner.vue
  layouts/default.vue
  pages/pix-pro/index.vue
  static/images/close-icon-black.svg
Labels: :rocket: Ready to Merge

#542 [TECH] Améliorer la condition d'affichage précisant si la locale est international dans le locale switcher en affichage réduit (PIX-8230)
  components/LocaleSwitcher/LocaleSwitcher.vue
  tests/components/LocaleSwitcher.test.js
Labels: :rocket: Ready to Merge, team-acces

#544 [TECH] Correction des vulnérabilités NPM (PIX-8254)
  .circleci/config.yml
  jest.config.js
  package-lock.json
  package.json
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-acces

#547 [BUGFIX] Rendre l'affichage des nouvelles actualités plus résilientes (PIX-8376)
  components/NewsItemCard.vue
Labels: :rocket: Ready to Merge, team-acces
