Repository 1024pix/pix-site, pull requests merged in 2023-01, with the labels that each got.

#456 [FEATURE] Fluidifier la navigation de l'utilisateur (PIX-6705)
  components/FooterSliceZone.vue
  components/HotNewsBanner.vue
  components/LanguageSwitcher/LanguageSwitcher.vue
  components/LanguageSwitcher/LanguageSwitcherSubMenu.vue
  components/LocaleLink.vue
  components/NavigationSliceZone.vue
  components/PixLink.vue
  components/slices/NavigationZone.vue
  nuxt.config.js
  tests/components/LanguageSwitcher.test.js
  tests/components/PixLink.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#457 [FIX] Correction de style sur la page de choix de locale
  components/LocaleLink.vue
  pages/pix-site/locale-choice.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#460 [TECH] Rendre le script npm run clean vraiment utile en supprimant le répertoire dist et pas node_modules
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge

#462 [BUGFIX] Fermer le Burger Menu à la navigation
  components/NavigationSliceZone.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge

#459 [FEATURE] Ne pas passer par la page `/locale-choice` pour choisir sa locale
  layouts/empty.vue
  layouts/home.vue
  pages/pix-site/index.vue
  pages/pix-site/locale-choice.vue
  tests/pages/pix-site/index.test.js
Labels: :rocket: Ready to Merge

#463 [BUGFIX] Stocker la préférence de locale "International Français"
  nuxt.config.js
  pages/pix-pro/index.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge

#464 [TECH] Utiliser les termes "locales" au lieu de "languages" (PIX-6772)
  components/BurgerMenuNav.vue
  components/LocaleSwitcher/LocaleSwitcher.vue
  components/LocaleSwitcher/LocaleSwitcherSubMenu.vue
  components/slices/ActionsZone.vue
  config/language/index.js
  config/localization/index.js
  config/localization/pix-pro.js
  config/localization/pix-site.js
  config/localization/translations/en-gb.js
  config/localization/translations/fr-be.js
  config/localization/translations/fr-fr.js
  config/localization/translations/fr.js
  config/localization/translations/index.js
  nuxt.config.js
  pages/pix-site/index.vue
  services/document-fetcher.js
  services/get-routes-to-generate.js
  services/link-resolver.js
  tests/components/BurgerMenuNav.test.js
  tests/components/LocaleSwitcher.test.js
  tests/components/__snapshots__/LocaleSwitcher.test.js.snap
  tests/components/slices/ActionsZone.test.js
  tests/config/language/index.test.js
  tests/config/localization/index.test.js
  tests/config/localization/pix-pro.test.js
  tests/config/localization/pix-site.test.js
  tests/services/get-routes-to-generate.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#467 [BUGFIX] Corrections d'accessibilité de la langue sur la page de choix de locale
  layouts/empty.vue
  pages/pix-site/index.vue
Labels: :rocket: Ready to Merge, team-evaluation, team-acces

#465 [TECH] Permettre de lancer les environnement de dev de .fr et .org en parallèle
  README.md
  nuxt.config.js
  package.json
  sample.env
  servers.conf.erb
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#468 [FEATURE] Reordonner les choix du language-switcher pour être iso avec la page d'accueil de Pix.org (PIX-6833).
  config/localization/pix-site.js
  tests/components/__snapshots__/LocaleSwitcher.test.js.snap
  tests/config/localization/pix-site.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#470 [FEATURE] Ne plus utiliser l'acronyme "FWB" (PIX-6843)
  components/LocaleSwitcher/LocaleSwitcher.vue
  config/localization/pix-pro.js
  config/localization/pix-site.js
  config/localization/translations/en-gb.js
  config/localization/translations/fr-be.js
  config/localization/translations/fr-fr.js
  config/localization/translations/fr.js
  tests/components/__snapshots__/LocaleSwitcher.test.js.snap
  tests/config/localization/pix-pro.test.js
  tests/config/localization/pix-site.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, cross-team

#469 [FEATURE] Ajouter la page de choix de locale sur pro.pix.org (PIX-6834).
  config/localization/pix-pro.js
  pages/pix-pro/index.vue
  pages/pix-pro/locale-home.vue
  services/filter-nuxt-pages.js
  tests/pages/pix-pro/index.test.js
  tests/services/filter-nuxt-pages.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#472 [TECH] Classer les dépendances (dependencies vs devDependencies) et supprimer les dépendances inutiles
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#475 [BUGFIX] Eviter l'erreur de déploiement quand une URL de la navigation n'est pas encore définie
  components/slices/NavigationZone.vue
  tests/components/slices/NavigationZone.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#473 [TECH] Supprimer le dossier lang du fichier `.slugignore`
  .slugignore
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, team-acces

#474 [TECH] Permettre l'ajout de logs dynamiquement grâce à une variable d'environnement.
  servers.conf.erb
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#466 [FEATURE] Faire en sorte que le cookie de langue de pix.org soit lisible sur app.pix.org (PIX-6904)
  plugins/locale-observer.js
  tests/plugins/locale-observer.test.js
Labels: Func Review OK, :rocket: Ready to Merge, team-acces
