Repository 1024pix/pix-site, pull requests merged in 2023-02, with the labels that each got.

#479 [TECH] Ajouter la config pour renovate
  .github/renovate.json
Labels: Tech Review OK, :rocket: Ready to Merge

#498 [TECH] Mettre à jour jest
  package-lock.json
  package.json
  tests/pages/pix-site/__snapshots__/locale-home.test.js.snap
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#499 [TECH] Passage à nuxt@2.16.0
  nuxt.config.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, team-evaluation

#502 [TECH] Ajouter un endpoint de géolocalisation (PIX-7084)
  servers.conf.erb
Labels: :rocket: Ready to Merge, team-acces

#504 [FEATURE] Appeler le service de géolocalisation depuis pix-site (PIX-7036)
  README.md
  config/url.js
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  sample.env
  services/should-show-out-of-france-banner.js
  tests/config/url.test.js
  tests/layouts/default.test.js
  tests/services/should-show-out-of-france-banner.test.js
Labels: :eyes: Tech Review Needed, :eyes: Func Review Needed, team-acces

#507 [DOC] Documenter les nouvelle variables d'env de pix-site introduites pour la géolocalisation (PIX-7200)
  README.md
Labels: :rocket: Ready to Merge, no-review-app

#510 [TECH] Corrige un warning sur l'usage du `nextTick`
  tests/pages/pix-pro/index.test.js
  tests/pages/pix-site/index.test.js
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#511 [BUGFIX] Corriger le positionnement du cookie locale en local en mode dev
  plugins/locale-observer.js
  tests/plugins/locale-observer.test.js
Labels: :rocket: Ready to Merge, team-acces

#513 [BUGFIX] Permettre de visionner la vidéo de la page d'accueil
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#505 [BUGFIX] Corriger la régression d'indexation des sites (PIX-7208).
  .circleci/config.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  tests/e2e/robot.spec.ts
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#512 [FEATURE] Afficher une bannière pour suggérer aux utilisateurs hors de France visitant pix.fr d'aller sur pix.org (PIX-7041)
  README.md
  assets/scss/globals/_colors.scss
  components/LocaleSuggestionBanner.vue
  config/localization/translations/en-gb.js
  config/localization/translations/fr-be.js
  config/localization/translations/fr-fr.js
  config/localization/translations/fr.js
  layouts/default.vue
  tests/components/LocaleSuggestionBanner.test.js
  tests/layouts/default.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-acces

#518 [BUGFIX]: Corriger le problème d'affichage de la bannière hors de France en affichage réduit
  components/NavigationSliceZone.vue
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces
