Repository 1024pix/pix-site, pull requests merged in 2024-03, with the labels that each got.

#621 [BUGFIX] Rétablir la preview Prismic (PIX-11390).
  pix-pro/services/get-routes-to-generate.js
  pix-site/services/get-routes-to-generate.js
  shared/components/NewsItemPost.vue
  shared/nuxt.config.ts
  shared/services/link-resolver.js
  shared/tests/services/link-resolver.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, cross-team

#623 [TECH] Remplacer l'utilisation du terme "language" par "locale" (PIX-11456)
  pix-pro/components/LocaleSwitcher.vue
  pix-site/components/LocaleSwitcher.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-acces

#622 Revert "[TECH] Sécuriser l'API Prismic avec un token (PIX-11429)."
  pix-pro/sample.env
  pix-pro/services/get-routes-to-generate.js
  pix-site/sample.env
  pix-site/services/get-routes-to-generate.js
Labels: :rocket: Ready to Merge

#608 [FEATURE] Migrer le nouveau centre d'aide Support en Nuxt 3 (PIX-11331).
  pages/pix-site/_custom-page.vue
  pages/pix-site/support/_persona-sub-list.vue
  pages/pix-site/support/faq/_faq-post.vue
  pages/pix-site/support/form/_support-form.vue
  pages/pix-site/support/index.vue
  pix-site/error.vue
  pix-site/pages/support/[slug].vue
  pix-site/services/get-routes-to-generate.js
  shared/components/EasiwareForm.vue
  shared/components/Support/SupportContact.vue
  shared/components/Support/SupportHeader.vue
  shared/components/Support/SupportPersonaCard.vue
  shared/pages/support/[persona-sub-list].vue
  shared/pages/support/faq/[faq-persona].vue
  shared/pages/support/faq/[faq-post].vue
  shared/pages/support/form/[support-form].vue
  shared/pages/support/index.vue
  shared/public/robots.txt
  shared/services/easiware.js
  shared/services/link-resolver.js
  shared/translations/en.js
  shared/translations/fr-be.js
  shared/translations/fr-fr.js
  shared/translations/fr.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#624 [FEATURE] Ajouter des tests pour le langage switcher et la page de choix des langues (PIX-11476)
  .circleci/config.yml
  pix-site/components/LocaleChoice.vue
  pix-site/package-lock.json
  pix-site/package.json
  pix-site/tests/integration/components/LocaleChoice.test.ts
  pix-site/tests/integration/components/LocaleSwitcher.test.ts
Labels: :rocket: Ready to Merge, team-acces

#630 [BUGFIX] Corriger les erreurs de pages Support pour les locales internationales
  shared/components/Support/SupportContact.vue
  shared/pages/support/faq/[faq-persona].vue
  shared/pages/support/faq/[faq-post].vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#598 [REFACTOR] Ajouter des CTAs dans les blocs de la slice multiple-blocks (PIX-11233).
  pix-pro/layouts/default.vue
  pix-site/layouts/default.vue
  shared/assets/scss/components/slices/features.scss
  shared/assets/scss/components/slices/process.scss
  shared/assets/scss/shared/_titles.scss
  shared/components/CtaButton.vue
  shared/components/slices/MultipleBlock.vue
Labels: Func Review OK, :rocket: Ready to Merge, team-evaluation

#631 [FEATURE] Ajout du néerlandais sur Pix Site (PIX-11338)
  .circleci/config.yml
  pix-pro/components/LocaleSwitcher.vue
  pix-site/components/LocaleChoice.vue
  pix-site/components/LocaleSwitcher.vue
  pix-site/i18n.config.ts
  pix-site/package-lock.json
  pix-site/package.json
  pix-site/tests/integration/components/LocaleChoice.test.ts
  pix-site/tests/integration/components/LocaleSwitcher.test.ts
  shared/components/slices/NavigationGroup.vue
  shared/composables/useLocaleCookie.ts
  shared/pages/index.vue
  shared/pages/locale-home.vue
  shared/pages/news/[slug].vue
  shared/pages/news/index.vue
  shared/pages/support/[persona-sub-list].vue
  shared/pages/support/faq/[faq-persona].vue
  shared/pages/support/faq/[faq-post].vue
  shared/pages/support/form/[support-form].vue
  shared/pages/support/index.vue
  shared/tests/composables/useLocaleCookie.test.ts
  shared/translations/en.js
  shared/translations/fr-be.js
  shared/translations/fr-fr.js
  shared/translations/fr.js
  shared/translations/nl-be.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-acces

#641 [BUGFIX] Réparer le prerender des pages enfants du centre d'aide
  pix-pro/services/get-routes-to-generate.js
  pix-site/nuxt.config.ts
  pix-site/services/get-routes-to-generate.js
  shared/services/link-resolver.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, cross-team

#638 [BUGFIX] Afficher complètement le sélecteur de langue sur la version mobile (PIX-11644)
  pix-site/package.json
  shared/components/BurgerMenu/BurgerMenu.vue
Labels: :rocket: Ready to Merge, team-acces

#642 [FEATURE] Afficher un loader sur les formulaires du centre d'aide (PIX-11718).
  shared/components/EasiwareForm.vue
  shared/services/easiware.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#636 [FEATURE] Ajouter un bloc d'embed dans le type slice-page (PIX-11234).
  shared/components/PrismicCustomSliceZone.vue
  shared/components/slices/Embed.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, cross-team

#643 [BUGFIX] Réparer le lien pour passer sur le site international (PIX-11655)
  pix-site/layouts/default.vue
  shared/components/LocaleSuggestionBanner.vue
  shared/composables/useShowOutOfFranceBanner.ts
  shared/translations/en.js
  shared/translations/fr-be.js
  shared/translations/fr-fr.js
  shared/translations/fr.js
  shared/translations/nl-be.js
Labels: :rocket: Ready to Merge, team-acces
