Repository 1024pix/pix-site, pull requests merged in 2024-05, with the labels that each got.

#656 modif redirections pour le support
  pix-pro/nginx/includes/rewrites.conf
  pix-site/nginx/includes/rewrites.conf
Labels: :eyes: Tech Review Needed, :rocket: Ready to Merge

#655 [TECH] Créer une Github action pour permettre le déploiement de pix-site et pix-pro sur Scaleway
  .github/workflows/docker-deployment.yml
  Dockerfile
  pix-site/README.md
  sample.env
  shared/tests/services/document-fetcher.test.js
Labels: :rocket: Ready to Merge, team-captains

#660 [BUGFIX] Enlever l'appel Prismic pour récupérer les dernières actualités en production (PIX-12739)
  shared/components/slices/LatestNews.vue
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team

#659 [BUGFIX] Améliorer le style de la grille de statistiques présentes en accueil (PIX-12737).
  shared/assets/scss/components/slices/statistics.scss
Labels: :rocket: Ready to Merge, team-evaluation, Design Review OK, cross-team
