Repository 1024pix/pix-site, pull requests merged in 2024-02, with the labels that each got.

#594 [FEATURE] Ajouter du style sur les formulaires du support pour le lien de redirection vers le centre d'aide
  services/easiware.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#595 [REFACTOR] Utiliser une seule page plus adaptable pour gérer la liste des personas support (PIX-10917).
  components/SupportPersonaCard.vue
  pages/pix-site/support/_persona.vue
  pages/pix-site/support/index.vue
  services/document-fetcher.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#596 [FEATURE] Créer la page article (PIX-10919).
  config/localization/translations/en.js
  config/localization/translations/fr-be.js
  config/localization/translations/fr-fr.js
  config/localization/translations/fr.js
  pages/pix-site/support/faq/_post.vue
  services/document-fetcher.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#597 [FEATURE] Ajouter les pages FAQ des personas support
  components/SupportContact.vue
  components/SupportHeader.vue
  components/SupportPersonaCard.vue
  pages/pix-site/support/_persona-sub-list.vue
  pages/pix-site/support/_persona.vue
  pages/pix-site/support/faq/_faq-persona.vue
  pages/pix-site/support/faq/_faq-post.vue
  pages/pix-site/support/faq/_post.vue
  pages/pix-site/support/form/_support-form.vue
  pages/pix-site/support/index.vue
  services/document-fetcher.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#599 [FEATURE] Amélioration des pages de support
  components/EasiwareForm.vue
  components/SupportContact.vue
  config/localization/translations/en.js
  config/localization/translations/fr-be.js
  config/localization/translations/fr-fr.js
  config/localization/translations/fr.js
  pages/pix-site/support/_persona-sub-list.vue
  pages/pix-site/support/faq/_faq-persona.vue
  pages/pix-site/support/form/_support-form.vue
  pages/pix-site/support/index.vue
  services/easiware.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#602 [BUGFIX] Réparer le locale-switcher
  pix-site/components/LocaleSwitcher.vue
  shared/nuxt.config.ts
Labels: :rocket: Ready to Merge

#604 [BUGFIX] Permettre de revenir sur .org après avoir été sur .fr depuis .org
  pix-site/components/LocaleChoice.vue
  pix-site/components/LocaleSwitcher.vue
Labels: :rocket: Ready to Merge

#605 [BUGFIX] Servir le bon dossier pour le bon domaine pour Pix Pro
  pix-pro/components/LocaleSwitcher.vue
  pix-pro/public/apple-touch-icon.png
  pix-pro/public/favicon-16x16.png
  pix-pro/public/favicon-32x32.png
  pix-pro/public/favicon.ico
  pix-pro/public/images/icn-help.svg
  pix-pro/scalingo.json
  pix-pro/servers.conf.erb
Labels: :rocket: Ready to Merge

#607 [BUGFIX] Nommer correctement les scripts Matomo
  pix-pro/public/scripts/start-matomo-event.js
  pix-site/public/scripts/start-matomo-event.js
Labels: :rocket: Ready to Merge

#609 [BUGFIX] Rétablir les bannières des hotnews
  shared/components/HotNewsBanner.vue
Labels: :rocket: Ready to Merge

#610 [BUGFIX] Ordonner les actualités par le champ date des articles (PIX-11389).
  shared/components/slices/LatestNews.vue
  shared/pages/news/index.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#618 [TECH] Amélioration de la configuration des tests (PIX-11420)
  pix-pro/nuxt.config.ts
  pix-pro/package-lock.json
  pix-pro/package.json
  pix-pro/sample.env.test
  pix-pro/vitest.config.ts
  pix-site/nuxt.config.ts
  pix-site/package-lock.json
  pix-site/package.json
  pix-site/playwright.config.ts
  pix-site/sample.env.test
  pix-site/tests/e2e/components/locale-choice.spec.ts
  pix-site/tests/e2e/components/locale-switcher.spec.ts
  pix-site/tests/e2e/layout/footer.spec.ts
  pix-site/tests/e2e/layout/header.spec.ts
  pix-site/tests/e2e/pages/index.spec.ts
  pix-site/vitest.config.ts
  shared/composables/useEnvironmentUrl.ts
  shared/composables/useLocaleCookie.ts
  shared/nuxt.config.ts
  shared/package-lock.json
  shared/package.json
  shared/pages/index.vue
  shared/tests/composables/useEnvironmentUrl.test.ts
  shared/tests/composables/useLocaleCookie.test.ts
  shared/vite.config.ts
  shared/vitest.config.ts
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-acces

#616 [FEATURE] Modifier le libellé du choix fr-BE sur la page d'accueil de pix.org (PIX-11226)
  pix-site/i18n.config.ts
  shared/translations/en.js
  shared/translations/fr-be.js
  shared/translations/fr-fr.js
  shared/translations/fr.js
Labels: :rocket: Ready to Merge, team-acces

#611 [BUGFIX] Corriger les liens "link-to" des articles (PIX-11400).
  shared/components/PixPrismicLink.vue
Labels: :eyes: Tech Review Needed, :eyes: Func Review Needed, team-evaluation

#619 [FEATURE] Ajouter sur la page de choix de locale, l'option "België (Nederlands)" (PIX-11227)
  pix-site/i18n.config.ts
  shared/components/slices/NavigationGroup.vue
  shared/pages/locale-home.vue
  shared/translations/nl-be.js
Labels: :rocket: Ready to Merge

#620 [FEATURE] Ajouter le choix nl-BE dans le locale switcher version desktop sur pix site (PIX-11228)
  pix-site/components/LocaleSwitcher.vue
Labels: :rocket: Ready to Merge, team-acces
