Repository 1024pix/pix-site, pull requests merged in 2024-04, with the labels that each got.

#650 [Tech] Rediriger la page enseignement-scolaire/enseignant-ou-personnel-de-direction vers la page support
  pix-site/servers.conf.erb
Labels: Tech Review OK, :rocket: Ready to Merge, team-captains

#637 [BUGFIX] Corriger la preview Prismic sur les fragments de documents (PIX-11601)
  shared/services/link-resolver.js
  shared/tests/services/link-resolver.test.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, cross-team

#651 [TECH] : Delete enseignement-scolaire/enseignant-ou-personnel-de-direction redirection to support.pix.org
  pix-site/servers.conf.erb
Labels: :rocket: Ready to Merge, team-captains
