Repository 1024pix/pix-site, pull requests merged in 2024-10, with the labels that each got.

#714 [FEATURE] MAJ de la metadescription du Centre d'aide(PIX-14175)
  shared/pages/support/index.vue
  shared/translations/en.js
  shared/translations/fr-be.js
  shared/translations/fr-fr.js
  shared/translations/fr.js
  shared/translations/nl-be.js
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-prescription

#718 [BUGFIX] Corriger le problème des locales disponibles non-identiques entre pix-site à pix-pro (PIX-14143)
  pix-pro/i18n.config.ts
  pix-pro/nuxt.config.ts
  pix-site/i18n.config.ts
  pix-site/nuxt.config.ts
  shared/composables/useLocaleCookie.ts
  shared/pages/index.vue
  shared/tests/composables/useLocaleCookie.test.ts
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-acces

#701 [BUGFIX] Réparer l'affichage des images en preview (PIX-14766)
  sample.env
  shared/nuxt.config.ts
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation, cross-team

#720 [BUGFIX] Réparer le burger menu du site vitrine (PIX-14793).
  shared/components/BurgerMenu/BurgerMenuSections.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, cross-team
