Repository 1024pix/pix-site, pull requests merged in 2024-06, with the labels that each got.

#657 [BUGFIX] Afficher la liste complète des locales disponibles sur mobile (PIX-12477)
  pix-pro/components/LocaleSwitcher.vue
  pix-pro/nuxt.config.ts
  pix-site/components/LocaleSwitcher.vue
  pix-site/nuxt.config.ts
  shared/components/BurgerMenu/BurgerMenuLocalesList.vue
Labels: :rocket: Ready to Merge, team-acces

#658 [BUGFIX] Rendre accessible le cookie "locale" pour tous les sous domaines pix.org (PIX-12448)
  .circleci/config.yml
  pix-site/tests/integration/components/LocaleSwitcher.test.ts
  shared/composables/useLocaleCookie.ts
  shared/nuxt.config.ts
  shared/tests/composables/useLocaleCookie.test.ts
Labels: :rocket: Ready to Merge, team-acces

#661 [BUGFIX] Inclure les images dans les builds
  pix-pro/package-lock.json
  pix-pro/package.json
  pix-site/package-lock.json
  pix-site/package.json
  shared/nuxt.config.ts
Labels: :rocket: Ready to Merge

#665 Revert "[BUGFIX] Inclure les images dans les builds"
  pix-pro/package-lock.json
  pix-pro/package.json
  pix-site/package-lock.json
  pix-site/package.json
  shared/nuxt.config.ts
Labels: :rocket: Ready to Merge

#662 [TECH] Utiliser la librairie @nuxt/eslint au lieu de @nuxt/eslint-config
  package-lock.json
  package.json
Labels: Tech Review OK, :rocket: Ready to Merge, team-acces, cross-team, dependencies

#668 [BUGFIX] Inclure les images dans les builds, deuxième essai
  pix-pro/nuxt.config.ts
  pix-pro/package-lock.json
  pix-pro/package.json
  pix-site/nuxt.config.ts
  pix-site/package-lock.json
  pix-site/package.json
  shared/components/BurgerMenu/BurgerMenuHeader.vue
  shared/components/FormPage.vue
  shared/components/NewsItemCard.vue
  shared/components/SharedFooterSliceZone.vue
  shared/components/Support/SupportHeader.vue
  shared/components/Support/SupportPersonaCard.vue
  shared/components/slices/Article.vue
  shared/components/slices/LogosZone.vue
  shared/components/slices/MultipleBlock.vue
  shared/components/slices/PageBanner.vue
  shared/components/slices/PageSection.vue
  shared/nuxt.config.ts
Labels: Tech Review OK, :rocket: Ready to Merge

#670 [BUGFIX] Ne pas rappatrier les assets de `images.prismic.io` sur Pix Pro
  pix-pro/nuxt.config.ts
  pix-site/nuxt.config.ts
  shared/nuxt.config.ts
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge

#671 [BUGFIX] Ne pas rappatrier les assets de `images.prismic.io` du tout
  pix-site/nuxt.config.ts
  shared/components/NewsItemCard.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge

#674 [BUGFIX] Télécharger tous les assets disponibles
  pix-pro/nuxt.config.ts
  pix-pro/package-lock.json
  pix-pro/package.json
  pix-site/nuxt.config.ts
  pix-site/package-lock.json
  pix-site/package.json
Labels: :rocket: Ready to Merge

#669 [BUGFIX] Rendre les formulaires support multilingues(PIX-12765).
  shared/components/EasiwareForm.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#675 [FEATURE] Réduire la taille des assets
  shared/components/NewsItemCard.vue
  shared/components/slices/Article.vue
Labels: :rocket: Ready to Merge

#676 [TECH] : Add default redirection for support.pix.org
  pix-site/servers.conf.erb
Labels: :rocket: Ready to Merge

#666 [TECH] Amélioration de l'expérience développeur : MAJ doc et npm scripts
  INSTALL.md
  README.md
  pix-pro/package.json
  pix-site/README.md
  shared/README.md
Labels: Tech Review OK, :rocket: Ready to Merge, cross-team
