Repository 1024pix/pix-site, pull requests merged in 2025-01, with the labels that each got.

#729 [FEATURE] Ajouter un carrousel de témoignages customisable (PIX-15828).
  pix-site/nuxt.config.ts
  pix-site/package-lock.json
  pix-site/package.json
  shared/assets/scss/components/slices/testimonials.scss
  shared/components/PrismicCustomSliceZone.vue
  shared/components/slices/MultipleBlock.vue
  shared/components/slices/Testimonials.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, cross-team

#733 [FEATURE] Ajouter un bloc d'onglets (PIX-15825).
  shared/components/PrismicCustomSliceZone.vue
  shared/components/slices/Tabs.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#732 chore: add information in readme
  README.md
Labels: Tech Review OK, :rocket: Ready to Merge, team-evaluation

#736 [FEATURE] Transformer l'image cliquable de fermeture de la bannière en bouton. (PIX-16144)
  shared/components/HotNewsBanner.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation

#737 [A11Y] Ajouter l'action close banner sur le bouton au lieu de l'image (PIX-16144 bis).
  shared/components/HotNewsBanner.vue
Labels: Func Review OK, :rocket: Ready to Merge, team-evaluation

#738 [BUGFIX] Rendre les blocs témoignages et onglets utilisables sur pix-pro (PIX-16238).
  pix-pro/nuxt.config.ts
  pix-pro/package-lock.json
  pix-pro/package.json
Labels: Func Review OK, :rocket: Ready to Merge, team-evaluation, cross-team

#740 [FEATURE] Ajouter un 2eme lien dans les sous-bloc de la slice MultipleBlocs (PIX-16162).
  shared/components/slices/MultipleBlock.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation, cross-team

#739 [BUGFIX] Améliorer le style responsive de la slice Onglets (PIX-16246).
  shared/assets/scss/components/slices/testimonials.scss
  shared/components/slices/Tabs.vue
Labels: Func Review OK, Tech Review OK, :rocket: Ready to Merge, team-evaluation
